<?php

namespace Tests\Unit\Console\Core\Infraestructure\Command;

use PHPUnit\Framework\TestCase;

class MakeDrinkCommandTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAssertTrue()
    {
        $this->assertTrue(true);
    }
}
